CC = mpixlcxx_r
CXX = mpixlcxx_r
CFLAGS = -g -O2
CXXFLAGS = -g -O2

ROSS = /g/g92/jain6/bilge/ROSS
CODES_BASE = /g/g92/jain6/bilge/codes_trace/codes-base
CODES_NET = /g/g92/jain6/bilge/codes_trace/codes-net
CHARMPATH = /g/g92/jain6/bilge/charm_bigsim/pami-bluegeneq-bigemulator

CODES_BASE_LIBS = -L${CODES_NET}/install/lib -L${CODES_BASE}/install/lib -L${ROSS}/install/lib -lcodes-base -lROSS -lm

